name: loki
services:
  olmo:
    build: 
      dockerfile: Dockerfile.olmo
    ports:
      - 8080:8080
    volumes:
      - ./models/olmo/:/models/
  llama:
    build:
      dockerfile: Dockerfile.llama
    ports:
      - 8081:8080
    volumes:
      - ./models/llama/:/models/
  qwen2:
    build:
      dockerfile: Dockerfile.qwen2
    ports:
      - 8082:8080
    volumes:
      - ./models/qwen2/:/models/
  gpt2:
    build:
      dockerfile: Dockerfile.gpt2
    ports:
      - 8083:8080
    volumes:
      - ./models/gpt2/:/models/
  zephyr:
    build:
      dockerfile: Dockerfile.zephyr
    ports:
      - 8084:8080
    volumes:
      - ./models/zephyr/:/models/
  phi3:
    build:
      dockerfile: Dockerfile.phi3
    ports:
      - 8085:8080
    volumes:
      - ./models/phi3/:/models/

    
