name: loki
services:
  olmo:
    build: 
      dockerfile: Dockerfile.olmo
    ports:
      - 8080:8080
  llama:
    build:
      dockerfile: Dockerfile.llama
    ports:
      - 8081:8080
  qwen2:
    build:
      dockerfile: Dockerfile.qwen2
    ports:
      - 8082:8080
